rules:
  - id: python.lang.correctness.exit.use-sys-exit
    languages:
      - python
    message: |
      Use `sys.exit` over the python shell `exit` built-in.
    pattern: exit($X)
    fix: sys.exit($X)
    severity: WARNING
