rules:
  - id: use-sys-exit
    languages:
      - python
    message: |
      Use `sys.exit` over the python shell `exit` built-in. `exit` is a helper
      for the interactive shell and is not be available on all Python implementations.
      https://stackoverflow.com/a/6501134
    pattern: exit($X)
    fix: sys.exit($X)
    severity: WARNING
