version: 2.1

orbs:
  codacy: codacy/base@12.1.2
  codacy_plugins_test: codacy/plugins-test@2.0.11

jobs:
  unit_tests:
    docker:
      - image: cimg/go:1.22.5
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: unit_tests
          command: go test $(go list ./... | grep -v /docs/)

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - unit_tests:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_docker_local
          cmd: |
            docker build --build-arg TOOL_VERSION=$(cat .tool_version) -t $CIRCLE_PROJECT_REPONAME:latest . 
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - unit_tests
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
